# Site settings
title: Fun Study
email: kimchinqin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog for study.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://funstudy.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /posts/:year/:month/:title

highlighter: pygments

exclude: [Makefile, Gemfile, Rakefile, README.md]

gems:
  - jekyll-archives

jekyll-archives:
  enabled:
    - year
    - month
    - tags
    - categories
  layout: archive
  layouts:
    year: archive-year
    month: archive-month
    tag: archive-tag
    category: category
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    tag: '/archives/tag/:name/'
    category: '/categories/:name/'

